%function ntuple = load_rings(rootFileName)
%
%Reads a ROOT NTuple generated by the TrigNtCalo/CBNTAA_TrigRinger package
% and returns its rings contents in Matlab format.
%
%Input parameters are:
%rootFileName -> The NTuple file name (str). Wildcards (ex: *.aan.root) are accepted. 
%
%Returns a structure matrix with the following fields:
%  lvl1_id : The LVL1 Id. 
%  roi_id : The RoI Id.
%  lvl2_eta : The refined (LVL2) Eta coordinate for the RoI.
%  lvl2_phi : The refined (LVL2) Phi coordinate for the RoI.
%  et : The Et for each RoI, as calculated by T2CaloEgamma.
%  rings : The generated rings.
%  eventNo : Number generated upon execution of load_rings. It is unique for an event.
%  roiNo : Number generated upon execution of load_rings. It identifies one RoI in a gethring of RoIs belonging to the same event.
%  t2ca_em_e : Energy (not ET!) deposited on the eletromagnetic calorimeters, as calculated by the T2CaloEgamma.
%  t2ca_eta: The refined (LVL2) Eta coordinate of the RoI, calculated by T2CaloEgamma.
%  t2ca_phi : The refined (LVL2) Phi coordineta of the RoI, calculated by T2CaloEgamma.
%  t2ca_eratio : T2CaloEgamma's Eratio variable.
%  t2ca_rcore : T2CaloEgamma's Rcore variable.
%  t2ca_had_e : Energy deposited on the hadronic calorimeters, as calculated by T2CaloEgamma.
%  t2ca_had_es0 : Energy deposited on the first sampling of the hadronic calorimeter, as calculated by T2CaloEgamma.
%

